import mongoose from "mongoose"
import dotenv from "dotenv"
import Question from "../models/Question"

dotenv.config()

const questions = [
  // Classic (50 questions)
  { theme: "Classic", text: "What's your favorite movie of all time?" },
  { theme: "Classic", text: "What's your favorite TV show?" },
  { theme: "Classic", text: "What's your favorite music genre?" },
  { theme: "Classic", text: "Who's your favorite artist or band?" },
  { theme: "Classic", text: "What's the last song you had stuck in your head?" },
  { theme: "Classic", text: "What's your favorite book or book genre?" },
  { theme: "Classic", text: "What's your favorite way to spend a lazy Sunday?" },
  { theme: "Classic", text: "Are you a morning person or a night owl?" },
  { theme: "Classic", text: "What's your ideal way to relax after a long day?" },
  { theme: "Classic", text: "What's your favorite season?" },
  { theme: "Classic", text: "Beach vacation or mountain getaway?" },
  { theme: "Classic", text: "What's your dream vacation destination?" },
  { theme: "Classic", text: "What's your favorite hobby?" },
  { theme: "Classic", text: "What's something you've always wanted to learn?" },
  { theme: "Classic", text: "What's your biggest pet peeve?" },
  { theme: "Classic", text: "What's your favorite color?" },
  { theme: "Classic", text: "What's your favorite sport to watch or play?" },
  { theme: "Classic", text: "What's your go-to karaoke song?" },
  { theme: "Classic", text: "What's your favorite childhood memory?" },
  { theme: "Classic", text: "What's your biggest fear?" },
  { theme: "Classic", text: "What's your dream job?" },
  { theme: "Classic", text: "What's your favorite holiday?" },
  { theme: "Classic", text: "What's your favorite type of weather?" },
  { theme: "Classic", text: "What's your favorite animal?" },
  { theme: "Classic", text: "What's your favorite board game or card game?" },
  { theme: "Classic", text: "What's your favorite video game?" },
  { theme: "Classic", text: "What's your favorite app on your phone?" },
  { theme: "Classic", text: "What's your favorite social media platform?" },
  { theme: "Classic", text: "What's your favorite podcast?" },
  { theme: "Classic", text: "What's your favorite YouTube channel?" },
  { theme: "Classic", text: "What's your favorite type of exercise?" },
  { theme: "Classic", text: "What's your favorite way to celebrate your birthday?" },
  { theme: "Classic", text: "What's your favorite childhood toy?" },
  { theme: "Classic", text: "What's your favorite smell?" },
  { theme: "Classic", text: "What's your favorite sound?" },
  { theme: "Classic", text: "What's your favorite quote or saying?" },
  { theme: "Classic", text: "What's your favorite piece of clothing?" },
  { theme: "Classic", text: "What's your favorite accessory?" },
  { theme: "Classic", text: "What's your favorite room in your house?" },
  { theme: "Classic", text: "What's your favorite time of day?" },
  { theme: "Classic", text: "What's your favorite way to spend a rainy day?" },
  { theme: "Classic", text: "What's your favorite way to spend a sunny day?" },
  { theme: "Classic", text: "What's your favorite childhood TV show?" },
  { theme: "Classic", text: "What's your favorite childhood movie?" },
  { theme: "Classic", text: "What's your favorite superhero?" },
  { theme: "Classic", text: "What's your favorite villain?" },
  { theme: "Classic", text: "What's your favorite fictional character?" },
  { theme: "Classic", text: "What's your favorite historical figure?" },
  { theme: "Classic", text: "What's your favorite decade?" },
  { theme: "Classic", text: "What's your favorite type of art?" },

  // Foodie Feels 🍕 (50 questions)
  { theme: "Foodie Feels 🍕", text: "What's your favorite comfort food?" },
  { theme: "Foodie Feels 🍕", text: "What's your go-to coffee or tea order?" },
  { theme: "Foodie Feels 🍕", text: "What's one food you could eat every day?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite restaurant or cuisine?" },
  { theme: "Foodie Feels 🍕", text: "Sweet or savory snacks?" },
  { theme: "Foodie Feels 🍕", text: "What's your ideal breakfast?" },
  { theme: "Foodie Feels 🍕", text: "What's a food you absolutely can't stand?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite dessert?" },
  { theme: "Foodie Feels 🍕", text: "Do you prefer cooking at home or eating out?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite pizza topping?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite ice cream flavor?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of pasta?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of bread?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of cheese?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite fruit?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite vegetable?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of meat?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite seafood?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of soup?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of salad?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite sandwich?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite burger topping?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of taco?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of sushi?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of curry?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of noodles?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of rice dish?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite breakfast cereal?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of pancake or waffle?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of egg dish?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of potato dish?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of chip or crisp?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite candy?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite chocolate?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite cookie?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite cake?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite pie?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of donut?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of pastry?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of beverage?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of juice?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of smoothie?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of milkshake?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of cocktail?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of wine?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite type of beer?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite condiment?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite spice or herb?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite cooking show?" },
  { theme: "Foodie Feels 🍕", text: "What's your favorite food memory?" },

  // Love & Affection ❤️ (50 questions)
  { theme: "Love & Affection ❤️", text: "What's your love language?" },
  { theme: "Love & Affection ❤️", text: "What's your ideal date night?" },
  { theme: "Love & Affection ❤️", text: "What's the most romantic gesture someone could do for you?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic movie?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite love song?" },
  { theme: "Love & Affection ❤️", text: "What's your idea of a perfect kiss?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite type of hug?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite pet name to be called?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to show affection?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to receive affection?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic gesture?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to celebrate an anniversary?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite type of flower?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic destination?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite couple activity?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to spend quality time together?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic comedy?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic quote?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to say 'I love you'?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite memory with your partner?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite thing about being in a relationship?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to surprise your partner?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite gift to give?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite gift to receive?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic holiday?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to celebrate Valentine's Day?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic book?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic poem?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to cuddle?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to hold hands?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic dinner?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic dessert?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic drink?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic setting?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic time of day?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic season?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic weather?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic scent?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic sound?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic color?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic outfit?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic accessory?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic hairstyle?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic makeup look?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic perfume or cologne?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic song to dance to?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic dance?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic game?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite romantic tradition?" },
  { theme: "Love & Affection ❤️", text: "What's your favorite way to end a perfect date?" },

  // Travel Goals ✈️ (50 questions)
  { theme: "Travel Goals ✈️", text: "What's your dream travel destination?" },
  { theme: "Travel Goals ✈️", text: "What's the best trip you've ever taken?" },
  { theme: "Travel Goals ✈️", text: "Beach vacation or city adventure?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite way to travel?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite country you've visited?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite city you've visited?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel memory?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite type of accommodation?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel activity?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel food?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel souvenir?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel photo?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel story?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel companion?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel season?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for relaxation?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for adventure?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for culture?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for food?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for nature?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for history?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for shopping?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for nightlife?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for romance?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for family?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for solo travel?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for budget travel?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel destination for luxury travel?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel app?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel website?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel blog?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel vlog?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel book?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel movie?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel show?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel documentary?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel podcast?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel quote?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel tip?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel hack?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel packing item?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel gadget?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel outfit?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel accessory?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel bag?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel shoes?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel snack?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel drink?" },
  { theme: "Travel Goals ✈️", text: "What's your favorite travel playlist?" },
  { theme: "Travel Goals ✈️", text: "What's your bucket list travel destination?" },

  // Daily Habits ☕ (50 questions)
  { theme: "Daily Habits ☕", text: "What's your morning routine?" },
  { theme: "Daily Habits ☕", text: "What's your evening routine?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to start the day?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to end the day?" },
  { theme: "Daily Habits ☕", text: "What's your go-to breakfast?" },
  { theme: "Daily Habits ☕", text: "What's your go-to lunch?" },
  { theme: "Daily Habits ☕", text: "What's your go-to dinner?" },
  { theme: "Daily Habits ☕", text: "What's your go-to snack?" },
  { theme: "Daily Habits ☕", text: "What's your go-to drink?" },
  { theme: "Daily Habits ☕", text: "What's your favorite daily habit?" },
  { theme: "Daily Habits ☕", text: "What's a habit you're trying to build?" },
  { theme: "Daily Habits ☕", text: "What's a habit you're trying to break?" },
  { theme: "Daily Habits ☕", text: "What's your favorite productivity hack?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to stay organized?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to stay motivated?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to relax?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to exercise?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to meditate?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to journal?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to read?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to learn?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to create?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to connect with others?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to spend alone time?" },
  { theme: "Daily Habits ☕", text: "What's your favorite daily ritual?" },
  { theme: "Daily Habits ☕", text: "What's your favorite self-care practice?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to practice gratitude?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to practice mindfulness?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to stay healthy?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to stay fit?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to stay hydrated?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to get fresh air?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to get sunlight?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to wind down?" },
  { theme: "Daily Habits ☕", text: "What's your favorite bedtime routine?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to wake up?" },
  { theme: "Daily Habits ☕", text: "What's your favorite alarm sound?" },
  { theme: "Daily Habits ☕", text: "What's your favorite time to wake up?" },
  { theme: "Daily Habits ☕", text: "What's your favorite time to go to bed?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to commute?" },
  { theme: "Daily Habits ☕", text: "What's your favorite podcast to listen to daily?" },
  { theme: "Daily Habits ☕", text: "What's your favorite music to listen to daily?" },
  { theme: "Daily Habits ☕", text: "What's your favorite app to use daily?" },
  { theme: "Daily Habits ☕", text: "What's your favorite website to visit daily?" },
  { theme: "Daily Habits ☕", text: "What's your favorite daily affirmation?" },
  { theme: "Daily Habits ☕", text: "What's your favorite daily goal?" },
  { theme: "Daily Habits ☕", text: "What's your favorite daily challenge?" },
  { theme: "Daily Habits ☕", text: "What's your favorite daily reward?" },
  { theme: "Daily Habits ☕", text: "What's your favorite daily reflection?" },
  { theme: "Daily Habits ☕", text: "What's your favorite way to track your habits?" },

  // Childhood Memories 🧸 (50 questions)
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood memory?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood toy?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood game?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood TV show?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood movie?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood book?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood song?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood snack?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood meal?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood dessert?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood drink?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood candy?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood birthday party?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood holiday?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood vacation?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood friend?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood pet?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood teacher?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood subject in school?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood sport?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood hobby?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood place?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood smell?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood sound?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood color?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood outfit?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood hairstyle?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood accessory?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood cartoon?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood video game?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood board game?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood card game?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood outdoor game?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood indoor game?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood playground?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood park?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood restaurant?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood store?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood tradition?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood bedtime story?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood lullaby?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood nursery rhyme?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood fairy tale?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood superhero?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood princess?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood animal?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood dinosaur?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood season?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood weather?" },
  { theme: "Childhood Memories 🧸", text: "What's your favorite childhood dream?" },
]

async function seedQuestions() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost:27017/know-me-better")
    console.log("[v0] Connected to MongoDB")

    // Clear existing questions
    await Question.deleteMany({})
    console.log("[v0] Cleared existing questions")

    // Insert new questions
    await Question.insertMany(questions)
    console.log(`[v0] Successfully seeded ${questions.length} questions`)

    // Verify counts per theme
    const themes = [
      "Classic",
      "Foodie Feels 🍕",
      "Love & Affection ❤️",
      "Travel Goals ✈️",
      "Daily Habits ☕",
      "Childhood Memories 🧸",
    ]

    for (const theme of themes) {
      const count = await Question.countDocuments({ theme })
      console.log(`[v0] ${theme}: ${count} questions`)
    }

    process.exit(0)
  } catch (error) {
    console.error("[v0] Error seeding questions:", error)
    process.exit(1)
  }
}

seedQuestions()
