import os
from pymongo import MongoClient

# MongoDB connection
MONGODB_URI = os.getenv("MONGODB_URI", "mongodb://localhost:27017/know-me-better")
client = MongoClient(MONGODB_URI)
db = client.get_database()
questions_collection = db["questions"]

# Clear existing questions
questions_collection.delete_many({})

# Question bank with all themes
questions_data = [
    {
        "theme": "Classic",
        "questions": [
            "What's your favorite comfort food?",
            "What's your go-to coffee or tea order?",
            "What's one food you could eat every day?",
            "What's your favorite restaurant or cuisine?",
            "Sweet or savory snacks?",
            "What's your ideal breakfast?",
            "What's a food you absolutely can't stand?",
            "What's your favorite dessert?",
            "Do you prefer cooking at home or eating out?",
            "What's your favorite pizza topping?",
            "What's your favorite movie of all time?",
            "What's your favorite TV show?",
            "What's your favorite music genre?",
            "Who's your favorite artist or band?",
            "What's the last song you had stuck in your head?",
            "What's your favorite book or book genre?",
            "What's your favorite way to spend a lazy Sunday?",
            "Are you a morning person or a night owl?",
            "What's your ideal way to relax after a long day?",
            "What's your favorite season?",
            "Beach vacation or mountain getaway?",
            "What's your love language?",
            "What's your ideal date night?",
            "What's the most romantic gesture someone could do for you?",
            "What's your dream vacation destination?",
            "What's your biggest pet peeve?",
            "What's your favorite hobby?",
            "What's something you're really good at?",
            "What's your biggest fear?",
            "What's your favorite childhood memory?",
            "What's your dream job?",
            "What's your favorite color?",
            "What's your favorite animal?",
            "What's your favorite sport to watch or play?",
            "What's your favorite holiday?",
            "What's your favorite type of weather?",
            "What's your favorite way to exercise?",
            "What's your favorite app on your phone?",
            "What's your favorite social media platform?",
            "What's your favorite type of music to listen to while working?",
            "What's your favorite type of art?",
            "What's your favorite type of dance?",
            "What's your favorite type of game?",
            "What's your favorite type of puzzle?",
            "What's your favorite type of joke?",
            "What's your favorite type of meme?",
            "What's your favorite type of video?",
            "What's your favorite type of podcast?",
            "What's your favorite type of blog?",
            "What's your favorite type of magazine?",
        ],
    },
    {
        "theme": "Foodie Feels 🍕",
        "questions": [
            "My all-time comfort food is…",
            "My guilty pleasure snack is…",
            "Sweet or spicy? I'll always choose…",
            "My favorite midnight snack is…",
            "My go-to coffee/tea order is…",
            "The best meal I've ever had was…",
            "My favorite cuisine is…",
            "I could eat this every day and never get tired of it…",
            "My favorite dessert is…",
            "My favorite breakfast food is…",
            "The one food I absolutely can't stand is…",
            "My favorite pizza topping is…",
            "My favorite ice cream flavor is…",
            "My favorite restaurant is…",
            "My favorite home-cooked meal is…",
            "My favorite street food is…",
            "My favorite drink (non-alcoholic) is…",
            "My favorite alcoholic drink is…",
            "My favorite fruit is…",
            "My favorite vegetable is…",
            "My favorite type of bread is…",
            "My favorite type of cheese is…",
            "My favorite type of pasta is…",
            "My favorite type of rice dish is…",
            "My favorite type of soup is…",
            "My favorite type of salad is…",
            "My favorite type of sandwich is…",
            "My favorite type of burger is…",
            "My favorite type of taco is…",
            "My favorite type of sushi is…",
            "My favorite type of curry is…",
            "My favorite type of noodles is…",
            "My favorite type of dumpling is…",
            "My favorite type of BBQ is…",
            "My favorite type of seafood is…",
            "My favorite type of meat is…",
            "My favorite cooking style is…",
            "My favorite food memory is…",
            "The dish I wish I could cook perfectly is…",
            "My favorite food to share with someone is…",
            "My favorite food festival or event is…",
            "My favorite food-related TV show is…",
            "My favorite celebrity chef is…",
            "My favorite food Instagram account is…",
            "The most adventurous food I've tried is…",
            "My favorite food from my childhood is…",
            "My favorite food to eat when I'm sad is…",
            "My favorite food to eat when I'm celebrating is…",
            "My favorite food combination that others find weird is…",
            "My dream food destination is…",
        ],
    },
    {
        "theme": "Love & Affection ❤️",
        "questions": [
            "My favorite thing about you is…",
            "Our first inside joke was about…",
            "My dream date night is…",
            "I feel most loved when you…",
            "The first gift you gave me was…",
            "My favorite memory with you is…",
            "The moment I knew I loved you was…",
            "My favorite way to show you I care is…",
            "The thing that makes me smile about you is…",
            "My favorite nickname for you is…",
            "The song that reminds me of you is…",
            "My favorite photo of us is…",
            "The thing I admire most about you is…",
            "My favorite way to spend time with you is…",
            "The thing that makes you unique is…",
            "My favorite thing you've said to me is…",
            "The moment I felt closest to you was…",
            "My favorite way you make me laugh is…",
            "The thing I'm most grateful for about you is…",
            "My favorite tradition we have together is…",
            "The thing I want to do with you someday is…",
            "My favorite way you support me is…",
            "The thing that makes our relationship special is…",
            "My favorite quality about you is…",
            "The moment I knew we were meant to be was…",
            "My favorite way to surprise you is…",
            "The thing I love most about your personality is…",
            "My favorite way to comfort you is…",
            "The thing that makes me feel safe with you is…",
            "My favorite way to celebrate with you is…",
            "The thing I want you to know is…",
            "My favorite way you show me love is…",
            "The thing that makes me proud of you is…",
            "My favorite way to make you happy is…",
            "The thing I appreciate most about our relationship is…",
            "My favorite way to connect with you is…",
            "The thing that makes me feel understood by you is…",
            "My favorite way to express my love for you is…",
            "The thing I want to experience with you is…",
            "My favorite way you inspire me is…",
            "The thing that makes me feel lucky to have you is…",
            "My favorite way to grow together is…",
            "The thing I want to tell you more often is…",
            "My favorite way you challenge me is…",
            "The thing that makes our bond strong is…",
            "My favorite way to dream about our future is…",
            "The thing I love most about loving you is…",
            "My favorite way to be there for you is…",
            "The thing that makes every day better with you is…",
            "My favorite way to say I love you is…",
        ],
    },
    {
        "theme": "Travel Goals ✈️",
        "questions": [
            "My dream travel destination is…",
            "The best trip I've ever been on was…",
            "The first trip I want to take with you is…",
            "Beach or mountains? I'll always choose…",
            "A city I'd love to live in is…",
            "My favorite travel memory is…",
            "The most beautiful place I've ever seen is…",
            "My ideal vacation length is…",
            "My favorite way to travel is (plane, train, car, etc.)…",
            "The country I want to visit most is…",
            "My favorite type of accommodation is…",
            "The adventure activity I want to try is…",
            "My favorite travel companion would be…",
            "The food destination I want to visit is…",
            "My favorite travel season is…",
            "The historical site I want to see is…",
            "My favorite type of vacation is…",
            "The natural wonder I want to visit is…",
            "My favorite travel souvenir is…",
            "The festival I want to attend is…",
            "My favorite travel photo spot is…",
            "The road trip I want to take is…",
            "My favorite travel app is…",
            "The cruise destination I want to visit is…",
            "My favorite travel budget is…",
            "The backpacking trip I want to do is…",
            "My favorite travel documentary is…",
            "The island I want to visit is…",
            "My favorite travel book is…",
            "The safari destination I want to visit is…",
            "My favorite travel playlist includes…",
            "The ski resort I want to visit is…",
            "My favorite travel Instagram account is…",
            "The diving spot I want to visit is…",
            "My favorite travel quote is…",
            "The hiking trail I want to do is…",
            "My favorite travel movie is…",
            "The wine region I want to visit is…",
            "My favorite travel memory with family is…",
            "The theme park I want to visit is…",
            "My favorite travel memory with friends is…",
            "The museum I want to visit is…",
            "My favorite solo travel destination is…",
            "The beach I want to visit is…",
            "My favorite travel bucket list item is…",
            "The castle I want to visit is…",
            "My favorite travel fear I want to overcome is…",
            "The temple I want to visit is…",
            "My favorite travel lesson I've learned is…",
            "The place I want to return to is…",
        ],
    },
    {
        "theme": "Daily Habits ☕",
        "questions": [
            "My favorite time of the day is…",
            "My morning ritual always includes…",
            "My go-to comfort activity is…",
            "I usually spend too much money on…",
            "I never leave home without…",
            "My favorite way to start the day is…",
            "My evening routine includes…",
            "My favorite productivity hack is…",
            "My go-to stress relief is…",
            "My favorite way to wind down is…",
            "My most productive time of day is…",
            "My favorite daily exercise is…",
            "My go-to healthy habit is…",
            "My favorite way to stay organized is…",
            "My daily self-care routine includes…",
            "My favorite way to stay motivated is…",
            "My go-to meal prep strategy is…",
            "My favorite way to stay hydrated is…",
            "My daily screen time habit is…",
            "My favorite way to stay connected with friends is…",
            "My go-to work break activity is…",
            "My favorite way to practice mindfulness is…",
            "My daily gratitude practice includes…",
            "My favorite way to stay creative is…",
            "My go-to learning habit is…",
            "My favorite way to stay informed is…",
            "My daily reading habit includes…",
            "My favorite way to stay active is…",
            "My go-to bedtime routine is…",
            "My favorite way to start the weekend is…",
            "My daily journaling habit includes…",
            "My favorite way to stay positive is…",
            "My go-to meal of the day is…",
            "My favorite way to stay focused is…",
            "My daily meditation practice includes…",
            "My favorite way to stay inspired is…",
            "My go-to weekend activity is…",
            "My favorite way to stay balanced is…",
            "My daily music listening habit includes…",
            "My favorite way to stay energized is…",
            "My go-to guilty pleasure is…",
            "My favorite way to stay social is…",
            "My daily podcast listening habit includes…",
            "My favorite way to stay curious is…",
            "My go-to comfort zone activity is…",
            "My favorite way to challenge myself daily is…",
            "My daily habit I'm most proud of is…",
            "My favorite way to end the day is…",
            "My go-to daily indulgence is…",
            "My favorite daily habit I want to build is…",
        ],
    },
    {
        "theme": "Childhood Memories 🧸",
        "questions": [
            "My favorite childhood toy was…",
            "My favorite cartoon growing up was…",
            "My favorite school lunchbox dish was…",
            "My favorite festival memory as a kid was…",
            "The teacher I'll never forget is…",
            "My favorite childhood game was…",
            "My favorite childhood book was…",
            "My favorite childhood movie was…",
            "My favorite childhood friend was…",
            "My favorite childhood vacation was…",
            "My favorite childhood birthday party was…",
            "My favorite childhood pet was…",
            "My favorite childhood hobby was…",
            "My favorite childhood sport was…",
            "My favorite childhood subject in school was…",
            "My favorite childhood snack was…",
            "My favorite childhood TV show was…",
            "My favorite childhood song was…",
            "My favorite childhood hiding spot was…",
            "My favorite childhood adventure was…",
            "My favorite childhood tradition was…",
            "My favorite childhood Halloween costume was…",
            "My favorite childhood Christmas memory was…",
            "My favorite childhood summer activity was…",
            "My favorite childhood winter activity was…",
            "My favorite childhood spring activity was…",
            "My favorite childhood fall activity was…",
            "My favorite childhood sleepover memory was…",
            "My favorite childhood school trip was…",
            "My favorite childhood talent show performance was…",
            "My favorite childhood science project was…",
            "My favorite childhood art project was…",
            "My favorite childhood music class memory was…",
            "My favorite childhood PE class memory was…",
            "My favorite childhood recess activity was…",
            "My favorite childhood cafeteria food was…",
            "My favorite childhood school event was…",
            "My favorite childhood family tradition was…",
            "My favorite childhood road trip was…",
            "My favorite childhood camping trip was…",
            "My favorite childhood amusement park visit was…",
            "My favorite childhood zoo visit was…",
            "My favorite childhood museum visit was…",
            "My favorite childhood beach day was…",
            "My favorite childhood park visit was…",
            "My favorite childhood library visit was…",
            "My favorite childhood movie theater experience was…",
            "My favorite childhood restaurant was…",
            "My favorite childhood ice cream flavor was…",
            "My favorite childhood memory overall is…",
        ],
    },
    {
        "theme": "Flirty Fun 😏🔥",
        "questions": [
            "The cutest thing you've done for me is…",
            "My favorite compliment from you was…",
            "The first time you made me blush was…",
            "My favorite romantic emoji is…",
            "The flirtiest text you ever sent me was…",
            "The thing that makes me weak in the knees is…",
            "My favorite way you flirt with me is…",
            "The moment I found you most attractive was…",
            "My favorite thing about your smile is…",
            "The thing you do that drives me crazy (in a good way) is…",
            "My favorite way to tease you is…",
            "The thing I love most about your eyes is…",
            "My favorite way you touch me is…",
            "The thing that makes me feel butterflies is…",
            "My favorite way to get your attention is…",
            "The thing I love most about your laugh is…",
            "My favorite way you make me feel special is…",
            "The thing that makes me want to kiss you is…",
            "My favorite way to make you smile is…",
            "The thing I love most about your voice is…",
            "My favorite way you surprise me is…",
            "The thing that makes me feel desired is…",
            "My favorite way to be close to you is…",
            "The thing I love most about your style is…",
            "My favorite way you look at me is…",
            "The thing that makes me feel connected to you is…",
            "My favorite way to hold you is…",
            "The thing I love most about your confidence is…",
            "My favorite way you make me laugh is…",
            "The thing that makes me feel attracted to you is…",
            "My favorite way to whisper to you is…",
            "The thing I love most about your playfulness is…",
            "My favorite way you challenge me is…",
            "The thing that makes me feel excited around you is…",
            "My favorite way to dance with you is…",
            "The thing I love most about your spontaneity is…",
            "My favorite way you make me feel alive is…",
            "The thing that makes me feel passionate is…",
            "My favorite way to be romantic with you is…",
            "The thing I love most about your charm is…",
            "My favorite way you make me feel wanted is…",
            "The thing that makes me feel electric is…",
            "My favorite way to be playful with you is…",
            "The thing I love most about your mystery is…",
            "My favorite way you make me feel beautiful/handsome is…",
            "The thing that makes me feel intrigued is…",
            "My favorite way to be adventurous with you is…",
            "The thing I love most about your intensity is…",
            "My favorite way you make me feel irresistible is…",
            "The thing that makes me want more of you is…",
        ],
    },
]

# Insert all questions
for theme_data in questions_data:
    theme = theme_data["theme"]
    for question_text in theme_data["questions"]:
        questions_collection.insert_one({"theme": theme, "text": question_text})

print(f"Successfully seeded {questions_collection.count_documents({})} questions across {len(questions_data)} themes!")
client.close()
